apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels: 
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
          # to referece value from secret we need to use valueFrom as flow:
            valueFrom: 
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-password
          - name: MONGO_INITDB_DATABASE
            value: "bff"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  # we said to the service connect to the pod name mongodb the info is on the deployment under:
  # template -> metadata -> labels -> app
  selector:
    app: mongodb
  ports:
  - protocol: TCP
  # service port
    port: 27017
  # container port
    targetPort: 27017
